### ISSUE TITLE
Wrong output when using --force-sugar and output redirection together

### ISSUE THREAD

**Issue by JoeMerten** [Teemu/pytest-sugar#120]
#### Command used to run py.test
````py.test --color=yes --force-sugar test_blah.py | tee output.txt````

See also https://github.com/jenkinsci/ansicolor-plugin/issues/53

**Comment by Frozenball** [comment]
I believe this is the same problem people [have been complaining with Docker.](https://github.com/Frozenball/pytest-sugar/pull/49)

PRs are welcome if someone finds a solution 🙂

**Comment by Teemu** [comment]
Closing an old issue. Feel free to open a new issue if issue still persists.
