### ISSUE TITLE
Missing git tags for new releases

### ISSUE THREAD

**Issue by felixonmars** [Teemu/pytest-sugar#137]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by Natim** [comment]
https://github.com/Frozenball/pytest-sugar/releases

**Comment by felixonmars** [comment]
@Natim The releases page only includes releases up to 0.3.3, but the current version is 0.9.2 on PyPI.

**Comment by kloczek** [comment]
Any update?

**Comment by Natim** [comment]
I think that's the way the project is released that makes it so. @Teemu would you consider using `zest.releaser` for your upcoming releases? It guess it would fix the issue at hand. If you want to I can take some time to backfill all the existing tags.

**Comment by justinmayer** [comment]
Hey @Natim! 👋 In a separate message to @Teemu, I recently made a similar proposal to use [AutoPub](http://justinmayer.com/projects/autopub/) to automate the release process and had intended to submit a PR to configure this project appropriately. That said, it doesn't matter to me which tool is used — streamlining the release process is the important part. 💫 

Either way, back-filling the existing tags seems like a great idea to me. 👍

**Comment by Teemu** [comment]
I didn't know about `zest.releaser`, that def looks handy. I have done all my changelog & versioning manually so far. 😅

I think AutoPub could be worth trying and would actually empower others. As far as the git tagging goes, I haven't had the need for it personally. Of course, if we switch to some proper deployment flow, we get that for free so that's nice.

**Comment by Natim** [comment]
It is mainly useful for dependabot or renovabot to display a changelog during dependencies upgrade. It also allow to go directly at the right source code place when we find a bug and want to read the code.

**Comment by kloczek** [comment]
Any progress about add missing git tags? (or at east last one) 😋

**Comment by justinmayer** [comment]
As a precursor to submitting a PR to automate `pytest-sugar` releases via [AutoPub](http://justinmayer.com/projects/autopub/), I would like to rename the primary branch from `master` to `main`. Any objections?

**Comment by justinmayer** [comment]
If by Monday 3 April there are no objections to renaming the primary branch, I will proceed and rename it to `main`. ✨

**Comment by auvipy** [comment]
main is ok

**Comment by Teemu** [comment]
It's ok. 👍

**Comment by justinmayer** [comment]
@Teemu: Turns out only you can do that. Would you mind using the following link to make that change? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by kloczek** [comment]
> main is ok

Still all tag is from 2014 and there is no tag for at last lat 0.9.6
https://github.com/Teemu/pytest-sugar/tags

**Comment by Teemu** [comment]
@justinmayer Done!
