### ISSUE TITLE
Outdated docs on website

### ISSUE THREAD

**Issue by michael-k** [Teemu/pytest-sugar#166]
https://pivotfinland.com/pytest-sugar/ still mentions the by now removed flag `--nosugar` instead of `-p no:sugar` in section *Usage*.

**Comment by blueyed** [comment]
Please consider creating a PR, possibly using `[ci skip]` in the commit message then.

**Comment by michael-k** [comment]
Against which repo?

**Comment by declension** [comment]
This just caught me out too. @Teemu how does the site get updated?

**Comment by Teemu** [comment]
I don't think it has a good deployment process at the moment. That lonely
server hosting that might have the only copy of the source code atm.

**Comment by Teemu** [comment]
Website has been removed
