### ISSUE TITLE
Progress bar background doesn’t honor the terminal settings

### ISSUE THREAD

**Issue by mcepl** [Teemu/pytest-sugar#182]
When running pytest with sugar in place on the terminal with light background, I get a very strange result with progress bar having a black background.

![Snímek z 2019-11-04 14-59-50](https://user-images.githubusercontent.com/198999/68126376-f1efd900-ff13-11e9-906d-560c2c240931.png)

Sugar should respect the terminal settings and use the light yellowish background I have (yes, the green bars will be less visible, but I guess that’s my problem for having a light background).

**Comment by Teemu** [comment]
I am not sure if we can respect the terminal settings -- I don't think we actually know the real colors. You can try theme.ini (I think it was named like that) for configuring the colors.

**Comment by blueyed** [comment]
@Teemu 
Shouldn't it just not use a background color?

**Comment by Teemu** [comment]
What would you replace it with? I don't think we can ensure that the block width = space width? Although I guess in this case since the progress is before the progress bar, we could just ignore the aligning (or try \t)

**Comment by blueyed** [comment]
`None` ?
Ref: https://github.com/Teemu/pytest-sugar/blob/66f6d9f9311a176ffafdfe00cb8c487d45b6a735/pytest_sugar.py#L48

@mcepl try configuring this maybe.
It currently appears to use "grey" (color 0).

**Comment by blueyed** [comment]
As for config: https://github.com/Teemu/pytest-sugar/blob/66f6d9f9311a176ffafdfe00cb8c487d45b6a735/pytest_sugar.py#L122-L139

**Comment by Teemu** [comment]
Hmm
