### ISSUE TITLE
Maintenance and possible move to under pytest-dev org

### ISSUE THREAD

**Issue by ssbarnea** [Teemu/pytest-sugar#184]
While I really LOVE `pytest-sugar` it saddens me to see it mainly unmaintained in the last 3 years. I am sure that sooner or later things will break and I would like to propose the following:

* move the project under https://github.com/pytest-dev to make it more official plugin, and where there are others that could give hand if needed
* add one or two more maintainers so they can at least review and merged incoming PRs before they get outdated

**Comment by Teemu** [comment]
Yeah I agree that the maintenance at least from my side has been pretty barebones -- I check it like once a year or if someone pings me! Luckily @blueyed has done amazing job with maintenance!

**Comment by ssbarnea** [comment]
I recently moved two of my plugins there, the process is documented at https://docs.pytest.org/en/stable/contributing.html#submitting-plugins-to-pytest-dev -- I really liked at as it makes maintenance easier as other pytest maintainers can easily help.

**Comment by graingert** [comment]
the contributing guidelines were recently changed: https://docs.pytest.org/en/latest/contributing.html#submitting-plugins-to-pytest-dev

**Comment by pradyunsg** [comment]
A gentle nudge on this -- @Teemu would you still be interested in making this transfer?

**Comment by ssbarnea** [comment]
@Teemu Any reason for not transferring the sweetener under pytest-dev?

**Comment by kevinmarsh** [comment]
@Teemu I really love the "show failing test output instantly" feature and was going to incorporate `pytest-sugar` into a project but the risk of it breaking in future versions of `pytest` without being resolved is a blocker for me. Transferring ownership to `pytest-dev` (or more active maintainership here) would help reduce that risk and would make it more likely for me (and hopefully others) to spend time contributing to the project to ensure ongoing compatibility with the Python/pytest ecosystem. Thanks

**Comment by graingert** [comment]
@ssbarnea I tried to use a PEP 541 request to move this to pytest-dev but it failed on reachability because @Teemu replied privately

**Comment by ssbarnea** [comment]
It seems that I was not wrong to stop adopting sugar to other project as that refusal and lack of transparency is clearly not a good sign.

**Comment by RonnyPfannschmidt** [comment]
Closing as the maintainer is not interested,

**Comment by RonnyPfannschmidt** [comment]
Whops, not under pytest-meta
