### ISSUE TITLE
pytest-plugin topic is missing

### ISSUE THREAD

**Issue by ssbarnea** [Teemu/pytest-sugar#189]
On this repository the `pytest-plugin` topic is not added, making much harder to find pytest-sugar as a plugin. Very easy to fix, but needs to be done by someone that can edit topics.

**Comment by ssbarnea** [comment]
If that was not addressed in 4 months, adding this plugin to your CI pipelines can be considered a serious liability. Unmaintained plugins are a liability, even those actively maintained by a single person can be considered so.

Thanks is bit sad as I kinda liked how sugar liked.

**Comment by Teemu** [comment]
That was added.
