### ISSUE TITLE
lots of project metadata is missing from setup.cfg

### ISSUE THREAD

**Issue by ssbarnea** [Teemu/pytest-sugar#192]
Current project listing on pypa is missing a lot of metadata including at least source code link, docs link, issue tracker link, list of open PRs/Bugs/starts.

Adding these should not be hard, just compare the setup.cfg with another project that lists them , example https://pypi.org/project/pytest-molecule/

**Comment by Teemu** [comment]
These were added by one of our contributors ❤️
