### ISSUE TITLE
General / non-technical improvement

### ISSUE THREAD

**Issue by snejus** [Teemu/pytest-sugar#202]
Wasn't sure where else to place this - hope it's fine. 

While I do love the package and its looks within the terminal, I was a bit perplexed to see that the website does not have the same standards - the biggest issue being is that it isn't friendly to people that have issues with their vision. There isn't enough contrast and it's quite hard to see anything with the background moving all the time. Also, the provided `pytest` link is dead.

It'd be good that it included a link to the github repo (I struggled to find it there, as well as on `pypi`). Having scrolled across the description which is mostly just broken markup, I found a link to some issue at the bottom. If you had 10 stars on github I would never care, but now considering that you have a rather strong following, it seems a bit off that considering the things I mentioned one could assume that the package is just unmaintained.

**Comment by Teemu** [comment]
Yeah I agree that the website needs work but this project has been on pretty bare-bones maintenance 😁.

**Comment by graingert** [comment]
@Teemu the github readme is already very good in terms of contrast and readability, I'd recommend moving the remaining content from the website https://pivotfinland.com/pytest-sugar/ to the README.rst and adding a permanent redirect from https://pivotfinland.com/pytest-sugar/ to https://github.com/Teemu/pytest-sugar/ for SEO juice

**Comment by Teemu** [comment]
I am now redirecting the webpage to this Github
