### ISSUE TITLE
Going towards 1.0 ... or at least "Production/Stable"

### ISSUE THREAD

**Issue by MartinThoma** [Teemu/pytest-sugar#208]
According to [the projects PyPI page](https://pypi.org/project/pytest-sugar/), pytest-sugar is in `Alpha` stage.

But I see indicators that this might be outdated:

* Age: The [first commit](https://pypi.org/project/pytest-sugar/) was in 2013.
* Community: pytest-sugar has 611 stars, 49 forks, and 32 contributors on GitHub
* Usage: Over [5000 projects](https://github.com/Teemu/pytest-sugar/network/dependents?package_id=UGFja2FnZS01MjUwMjg3NQ%3D%3D) use it
* Releases: 26 releases on PyPI
* Continuous Integration: Exists, but the build is broken at the moment

This does not sound like "Alpha" stage. More like [`Development Status :: 5 - Production/Stable`](https://pypi.org/classifiers/). And a stable release sounds more like 1.x than a [0ver](https://0ver.org/).

What do you think about updating?

**Comment by Teemu** [comment]
I am not sure if I could call this project really a stable yet since we don't support all flags that pytest does.

**Comment by Teemu** [comment]
I updated the classification to beta

**Comment by MartinThoma** [comment]
Sorry, I didn't see this and forgot I wrote it already :see_no_evil: 

> I updated the classification to beta

Cool! Did you push it?
