### ISSUE TITLE
The demo video is missing

### ISSUE THREAD

**Issue by mgedmin** [Teemu/pytest-sugar#214]
http://pivotfinland.com/pytest-sugar/img/video.gif now redirects to https://github.com/Teemu/pytest-sugar/img/video.gif which is a 404 page.

Suggestion: if you still have that file, add it to a git repository (this one if it's not too huge, or maybe some sibling repository pytest-sugar-demo) and link to it using a raw link like `https://raw.githubusercontent.com/Teemu/pytest-sugar/master/video.gif`.

**Comment by graingert** [comment]
fyi it's still on wayback

https://web.archive.org/web/20200429105636/https://pivotfinland.com/pytest-sugar/img/video.gif

![image](https://user-images.githubusercontent.com/413772/93016557-11d33d00-f5ba-11ea-8ed8-91bd92205947.png)

**Comment by graingert** [comment]
and it's only: 4.83 KB (4,949 bytes)

I'd recommend re-recording it with asciinema/svg-term-cli: https://github.com/marionebl/svg-term-cli

**Comment by graingert** [comment]
<p align="center">
  <img width="600" src="https://cdn.rawgit.com/marionebl/svg-term-cli/1250f9c1/examples/parrot.svg">
</p>

**Comment by Teemu** [comment]
Oops, this happened when I redirected the website to this repo. Fixed now.
