### ISSUE TITLE
New co maintainer

### ISSUE THREAD

**Issue by auvipy** [Teemu/pytest-sugar#224]
We use this library in celery project. I would like to help as co maintainer off this project.

**Comment by mxschmitt** [comment]
cc @Teemu

**Comment by max-sixty** [comment]
@graingert @auvipy do you think it might be time to fork it? It's a great project, it would be a shame to see its demise. (Ofc if @Teemu wanted to restart maintenance, that would be awesome)

**Comment by graingert** [comment]
Rather than a fork, energy seems to be coalescing behind https://github.com/nicoddemus/pytest-rich

**Comment by max-sixty** [comment]
Nice, thanks @graingert , it looks good!

**Comment by samuelcolvin** [comment]
pytest-sugar is awesome, @Teemu would be great if you could add more maintainers. I'd be happy to help too.

I hoped pytest-rich would be a solution, but development of that seems to have stopped too.

Another option would be to move pytest-sugar to the pytest org, we'd need to check if they were willing to accept the repo, but if so, I think that would be the best solution.

**Comment by hugovk** [comment]
The [checklist](https://docs.pytest.org/en/7.0.x/contributing.html#submitting-plugins-to-pytest-dev) for submitting to the pytest org is virtually complete:

* [x] PyPI presence with packaging metadata that contains a pytest- prefixed name, version number, authors, short and long description.

* [x] a [tox configuration](https://tox.readthedocs.io/en/latest/config.html#configuration-discovery) for running tests using [tox](https://tox.readthedocs.io/).

* [x] a README describing how to use the plugin...

* [ ] ... and on which platforms it runs.

* [x] a LICENSE file containing the licensing information, with matching info in its packaging metadata.

* [x] an issue tracker for bug reports and enhancement requests.

* [x] a [changelog](https://keepachangelog.com/).

**Comment by samuelcolvin** [comment]
I know pytest-sugar runs on (at least) ubuntu, macos, windows since I use it on CI on those platforms, so I think the checklist is complete.

**Comment by RonnyPfannschmidt** [comment]
With the current track record i don't want to have it in pytest-dev

**Comment by samuelcolvin** [comment]
Which track record?

**Comment by RonnyPfannschmidt** [comment]
maintainer communication and maintenance, currently i consider pytest-sugar a dead project that someone else would have to maintain

pytest-dev is not supposed to resurrect "zombies" - the people in it didn't sign up to collect maintenance liabilities

**Comment by samuelcolvin** [comment]
I totally get where you're coming from, and this entire question might be irrelevant if the current owner @Teemu isn't willing to move the project or add other maintainers.

But personally, as a day-in-day-out user (and massive fan :pray:) of pytest and pytest-sugar I think pytest-sugar enormously improves pytest, so I wondered if the pytest organisation might be willing to be a new home for this project?

Especially since, as @hugovk points out, there's specific provision for pytest plugins being added to the pytest org.

Regardless, I'd be happy to become a primary maintainer of pytest-sugar if @Teemu agrees.

**Comment by RonnyPfannschmidt** [comment]
in case additional maintainers demonstrate the project is alive and well i'm happy to welcome it

**Comment by samuelcolvin** [comment]
After @RonnyPfannschmidt's completely reasonable response, and having a look at pytest-sugar's code, I decided it's not worth the effort required to maintain it (at least for me).

I also realised I didn't care about much of the stuff that makes pytest-sugar output "fancy", but also very complex to maintain.

I've therefore created [pytest-pretty](https://github.com/samuelcolvin/pytest-pretty) which re-implements the bits of pytest-sugar I needed, hope it helps others needing similar functionality.

**Comment by Teemu** [comment]
Hey 👋 

As you might have noticed, I don't have much interest in maintaining this plugin. It works for my personal use as it is so I haven't had much motivation to fix issues people have. After all, this is completely voluntary work and not sponsored by any corporate (applies to most of us, of course) 😕

Although I wouldn't say it's completely dead, I do give it annual updates. 

> having a look at pytest-sugar's code, I decided it's not worth the effort required to maintain it (at least for me).

I can relate to this. This extension started off as a hack that I never really intended as production-quality software. I think it's still marked as "Alpha" on PyPi. Maintaining it has been rather painful as being dependent on pytest internals means breakages outside of my control.

Maybe the best way forward might be that pytest incorporates some of the ideas on this project into the core project itself.

ps. huge fan of Pydantic ❤️

**Comment by samuelcolvin** [comment]
Thanks @Teemu for the response, and kind words.

> Maybe the best way forward might be that pytest incorporates some of the ideas on this project into the core project itself.

I agree, an easy way to print some kind of error summary or traceback in real time as errors happen and adding line number to error summary would be huge wins.

Thanks again for pytest-sugar, I've used it masses over the last 5 years :raised_hands:.

**Comment by RonnyPfannschmidt** [comment]
bits of pytest are already moving in the direction of sugar,
i'd love to make it more easy to do things like sugar with less internals pain (time is a constraint)

in particular i'd like to enable having rich/textual based ux for pytest thats not a utter pain

**Comment by Teemu** [comment]
@justinmayer reached out and offered to help. I gave him maintainer access.

**Comment by auvipy** [comment]
thank I received maintainer ship as well. thanks
