### ISSUE TITLE
Missing git tag

### ISSUE THREAD

**Issue by kloczek** [Teemu/pytest-sugar#226]
According to https://pypi.org/project/pytest-sugar/ latest version is 0.9.4 however there is no here in the repo tag for that version.

**Comment by kloczek** [comment]
gentle ping 😃

**Comment by kloczek** [comment]
Really please add at least last release tag.
Without that it is now hard to track what has been added/fixed since last release 😞

**Comment by Teemu** [comment]
Duplicate of https://github.com/Teemu/pytest-sugar/issues/137
