### ISSUE TITLE
Broken support for Python 3.6

### ISSUE THREAD

**Issue by xkszltl** [Teemu/pytest-sugar#262]
This commit breaks python 3.6 compatibility due to termcolor 2 requiring >= python 3.7.
- https://github.com/Teemu/pytest-sugar/pull/259
- https://github.com/Teemu/pytest-sugar/commit/6b82c48c4cadefc6f26eed3662863292e1c77101

And, seems you forgot to update tox.ini:
- https://github.com/Teemu/pytest-sugar/blob/b42404819db5c09b9337dd1e3a7a95c5744c7e60/tox.ini#L12

**Comment by xkszltl** [comment]
@auvipy

**Comment by xkszltl** [comment]
Also, would be nice if the commit can be tagged when releasing wheels.
That would help people installing pytest-sugar from source.

**Comment by justinmayer** [comment]
Given that Python 3.6 has reached its end-of-life and is no longer supported, I don’t see any problem with a dependency that requires Python 3.7+.

Ergo, I personally don’t believe there is anything to be fixed here.

**Comment by auvipy** [comment]
yeah we should stop mentioning python 3.6

**Comment by xkszltl** [comment]
- Python 3.6 still exist in in several popular distros, including CentOS 7/RHEL 7/Ubuntu 18.04.
- Aside from that, if you plan to stop supporting old python, at least mark it in metadata. Currently pytest-sugar still says it supports much older python, so I believe this is an unintended regression.

**Comment by auvipy** [comment]
python 3.6 is EOL. the OS  that supports python 3.6 should use either the older version of this library or patch it as they need as they are doing patching the old python versions. But from a end users point of view, no one should use system python or a python version that is EOL. and use pyenv to install python version for development environment.

**Comment by justinmayer** [comment]
> Python 3.6 still exist in in several popular distros, including CentOS 7/RHEL 7/Ubuntu 18.04.

That is due to packaging decisions made by those distributions and is beyond our control. The remediations Asif mentioned are available to users of those older distribution versions.

> Aside from that, if you plan to stop supporting old python, at least mark it in metadata.

Dropping support for Python 3.6 is not *planned* — it is already *done*. The README already states the higher required Python version.

As far as the PyPI classifier metadata is concerned, Asif removed it in #263.

Regarding this specific issue, is there anything further outstanding?

**Comment by xkszltl** [comment]
> no one should use system python or a python version that is EOL

I know that's kind of the suggested "best practice" in python world, but there're a lot of valid reasons to use either system python or old python, especially when interact with non-python code in system. But that's a much broader topic outside of this thread. Just bring this up for awareness.

> As far as the PyPI classifier metadata is concerned

Yes that would make this much clear, thanks!

> Regarding this specific issue, is there anything further outstanding?

As mentioned above, would be nice if the commit can be tagged when releasing wheels.
It'll be very helpful for people using old python to stick to old version when pulling from source.
I believe this is also a general practice adopted by most python libs.

Also, metadata based resolver does not always work well for version fallback, when seeing newer version without python3.6 support but still marked as 3.6-compatible.

**Comment by xkszltl** [comment]
> no one should use system python or a python version that is EOL

I know that's kind of the suggested "best practice" in python world, but there're a lot of valid reasons to use either system python or old python, especially when interact with non-python code in system. But that's a much broader topic outside of this thread. Just bring this up for awareness.

> As far as the PyPI classifier metadata is concerned

Yes that would make this much clear, thanks!

> Regarding this specific issue, is there anything further outstanding?

As mentioned above, would be nice if the commit can be tagged when releasing wheels.
It'll be very helpful for people using old python to stick to old version when pulling from source.
I believe this is also a general practice adopted by most python libs.

Also, metadata based resolver does not always work well for version fallback, when seeing newer version without python3.6 support but still marked as 3.6-compatible.

**Comment by xkszltl** [comment]
> the OS that supports python 3.6 should use either the older version of this library or patch it as they need as they are doing patching the old python versions.

A side node regarding this comment.

I'm not a distro maintainer, but also did some packaging work.
If from their perspective, I would say:
- Each distro version typically have >=5 year life.
- Python has 3.5 year life.
- Distro should not have breaking change within a major version.
- Python usually has breaking change across major versions.
- Python libs rarely back-port security patches.
- Python libs often have a much larger dependency graph than typically C/C++ libs, resulting in more frequently security alerts.
- Python libs do not always offer accurate metadata or dependency graph.

So it would be quite challenging for distro to "use either the older version of this library or patch it as they need" in reality.

Still, this is not trying to draw any specific conclusion on the Issue itself, but just for discussion and awareness.

**Comment by Teemu** [comment]
Hey 👋 

My arbitrary guideline for Python version compatibility is to support the last two versions of Ubuntu LTS. So if you are running on Ubuntu 20.04 LTS, you are still supported (Python 3.8). So the next jump to Python 3.10 will be in 2024 when Ubuntu 24.04 LTS will be released.

I think that's plenty of time for people to upgrade. There's not much work to support older versions, so I'm not violently opposing older versions, but I don't think there is much to be gained by supporting older versions forever. Maintainer happiness also counts.

Besides, the old versions still work so no pressure to update.

**Comment by xkszltl** [comment]
> Maintainer happiness also counts.

Strongly agree.

> Besides, the old versions still work so no pressure to update.

Actually we hit this issue because in some deployment we're forced to upgrade.

Here's the background in case you're interested:
For purely offline deployment, using pip wheel from pypi is not possible, and using a binary is not optimal either, so instead we choose to install from local git mirror.
However because there's no versioned tag, we cannot `git clone -b old_version`.
That's why I also mentioned tagging released versions in this thread.

**Comment by xkszltl** [comment]
Close given tox is fixed and seems there's no plan for 3.6 compatibility.
Feel free to keep commenting and discussion.

Still, highly suggest to tag release versions, or at least tag versions with breaking changes.

**Comment by Teemu** [comment]
I think @justinmayer was planning on setting up some deployment stuff so maybe that will solve tagging as well?

**Comment by justinmayer** [comment]
Indeed, I hope to find some time to automate the release process sometime this month.
