### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by justinmayer** [Teemu/pytest-sugar#269]
In an effort to avert the absurdity that is [ZeroVer](https://0ver.org), I propose the next `pytest-sugar` release be anointed `v1.0.0`, perhaps in conjunction with officially dropping support for Python 3.7, which will very soon reach its [end-of-life date](https://endoflife.date/python).

**Comment by vladgurovich** [comment]
Thanks @justinmayer -- I do wish that would have happened before the pytest requirements were [increased by several major versions](https://github.com/Teemu/pytest-sugar/commit/6b82c48c4cadefc6f26eed3662863292e1c77101#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L45) in v0.9.7:

**Comment by auvipy** [comment]
we can keep 3.7 in the v1.0.0 release and drop in next release v1.1.0

**Comment by justinmayer** [comment]
@vladgurovich: It was not clear that those minimum Pytest version changes were not already in a shipped release — otherwise I would have indeed pushed for this last release to be `v1.0.0`. In any case, I do not know that there's much we can do about that now, right?

@auvipy: I do not understand. What would that achieve? Python 3.7 is already the minimum supported version.

**Comment by auvipy** [comment]
yes and just keeping that until v1.0.0 unless it is released few months later of EOL of 3.7 will llet users of old systems easier path to upgrade.

**Comment by justinmayer** [comment]
I'm not sure what will change in the next two months to make it easier for folks on older systems to upgrade from Python 3.7 to a newer version, so personally I don't think the stated reason is enough to warrant waiting until June to require Python 3.8+.

Other popular packages have already made this change: Flake8, isort, etc.

**Comment by auvipy** [comment]
celery hasn't dropped it yet and will wait until june and next major release v5.3 will include py3.7, although I wanted to drop it but celery is used by lots of old system & big enterprise, so we can't be too aggresive in dropping support.

**Comment by hugovk** [comment]
pytest 8.0.0 was released yesterday:

https://docs.pytest.org/en/latest/changelog.html#pytest-8-0-0-2024-01-27

Please could you make a new release with the https://github.com/Teemu/pytest-sugar/pull/278 fix? It's needed to use pytest-sugar with pytest 8.

Thanks!

**Comment by justinmayer** [comment]
Indeed — once #280 has been merged, I will prepare a release. 👍

**Comment by justinmayer** [comment]
I merged #280 and submitted PR #281. When the latter PR is merged, `pytest-sugar` v1.0.0 will be automatically released.

**Comment by justinmayer** [comment]
[`pytest-sugar` 1.0.0 has been released](https://github.com/Teemu/pytest-sugar/releases/tag/v1.0.0), and the package is now available on PyPI 🎉
