### ISSUE TITLE
`SugarTerminalReporter` access undeclared field `no_header`

### ISSUE THREAD

**Issue by AntonKueltz** [Teemu/pytest-sugar#270]
#### Command used to run pytest
````pytest <any test suite>````

#### Output
````
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/_pytest/main.py", line 189, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pluggy/manager.py", line 78, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<scrubbed>/lib/python3.8/site-packages/pytest_sugar.py", line 265, in pytest_sessionstart
INTERNALERROR>     if self.no_header:
INTERNALERROR> AttributeError: 'SugarTerminalReporter' object has no attribute 'no_header'
````

#### System Info
platform: darwin, Python 3.8.14, pytest 5.4.1

#### Summary
I believe [this line](https://github.com/Teemu/pytest-sugar/blob/main/pytest_sugar.py#L265) is the issue as `no_header` is not a field of the class `self` refers to. As far as I can tell this bug was introduced in v0.9.7. Is the cause here that pytest-sugar requires a newer version of pytest now?

**Comment by justinmayer** [comment]
Hi @AntonKueltz. This is not a bug, but rather the addition of support for a feature that requires Pytest 6+, which is already noted as the minimum supported version in this repo's README.

**Comment by AntonKueltz** [comment]
Is there no way to codify this in dependency versions / package metadata? Even if the README indicates the minimum version support, I don't think that's going to prevent pip from installing incompatible versions of the two packages right?

**Comment by AntonKueltz** [comment]
Edit - looks like this package [does define it](https://github.com/Teemu/pytest-sugar/blob/main/setup.py#L45), but pip isn't respecting the version constraint in my case. 🤷‍♂️ Agree, no bug on pytest-sugar's side here.

**Comment by justinmayer** [comment]
Indeed, there is a defined version constraint, and in my testing in a fresh Python 3.8.16 virtual environment with Pytest 5.4.1 installed, running `pip install pytest-sugar` will cause Pip to automatically upgrade Pytest to >= 6.2 — in my case, to 7.3.0. So at least for me, Pip's dependency resolution is behaving properly.
