### ISSUE TITLE
Request: configuring `termcolor` or `colorama` for color

### ISSUE THREAD

**Issue by jamesbraza** [Teemu/pytest-sugar#283]
As of https://github.com/Teemu/pytest-sugar/blob/v1.0.0/setup.py#L44, `pytest-sugar` depends on `termcolor`.

It would be cool if it could be configured to choose `colorama` over `termcolor`, mainly because many major packages use `colorama` already (e.g. `pytest`, `ipython`, `uvicorn`, `pygments` `pytest`, `tqdm`, `click`), not `termcolor`. Moving to `colorama` would be one less package installation.

Thank you for your consideration

**Comment by RonnyPfannschmidt** [comment]
Colorama itself recommends using termcolor or others for coloring

The primary focus of colorama is translating Andi to Windows legacy terminal API calls

**Comment by jamesbraza** [comment]
Oh ha, thanks for sharing. I didn't realize that. Going to close this out then, cheers
