### ISSUE TITLE
Clarify open-source license type

### ISSUE THREAD

**Issue by mociepka** [Teemu/pytest-sugar#284]
Could you consider using an established open-source license for this project? [Pytest](https://github.com/pytest-dev/pytest/blob/main/LICENSE) uses the MIT license, which might be a suitable option. With the current license, I am unable to use this project in my work. I understand that the library code will not be used in production directly (as it is a development dependency), but the current licensing still limits users who are bound by company policies that mandate the use of open-source software only.

Thank you for your consideration.

**Comment by justinmayer** [comment]
As one of the maintainers of this project, I agree and hereby second this motion. 👍 

While I am normally partial to (A)GPL licenses, in this case I do not have a strong opinion regarding which [OSI-compliant license](https://opensource.org/licenses) is selected.

**Comment by Teemu** [comment]
Isn't this a pretty established license? https://opensource.org/license/bsd-3-clause

I would have probably chosen MIT if given the choice, but we are pretty much stuck since there are too many contributors to relicense.

**Comment by justinmayer** [comment]
I had no idea the current `LICENSE` file in this project is based on one of the BSD licenses, albeit an older version that is not commonly seen in active use today. I suspect Michał did not realize that either.

That said, I think there are some changes I would suggest to improve the current situation:

1. Remove the "All rights reserved" line, which appeared in older versions of the BSD License but is not actually present in the [3-Clause BSD License](https://opensource.org/license/bsd-3-clause).
2. Ensure that the license type (e.g., "3-Clause BSD License") is clearly visible somewhere on the [main project page on GitHub](https://github.com/Teemu/pytest-sugar). (This may [happen automatically](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) once item 1. above is resolved.)

As to why the "All rights reserved" line was removed from modern versions of the BSD license, and why I think it should be removed from this project's license, please read: https://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved/4403#4403

@Teemu: Do you have any objections if I make the above change, bringing the project's `LICENSE` file in alignment with the [3-Clause BSD License](https://opensource.org/license/bsd-3-clause)?
