### ISSUE TITLE
Look at "progress" module on PyPI

### ISSUE THREAD

**Issue by msabramo** [Teemu/pytest-sugar#53]
pip git develop is vendoring progress==1.2 to display a download progress bar. Theirs is ASCII but it looks to have an `IncrementalBar` class that looks like it might be similar to pytest-sugar's. 

https://pypi.python.org/pypi/progress

Wondering if it might simplify pytest-sugar or handle anything nicer.

**Comment by Teemu** [comment]
Closing an old issue. Feel free to open a new issue if issue still relevant.
